# Generated by Django 3.2.10 on 2021-12-16 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211216_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='privilege',
            field=models.ForeignKey(default='User', on_delete=django.db.models.deletion.CASCADE, related_name='user_privilege', to='users.privilege'),
        ),
    ]
