# Generated by Django 3.2.10 on 2021-12-16 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_privilege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='sector',
            field=models.ForeignKey(default='Multiple', on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_sector', to='users.sector'),
        ),
    ]
